// Deno Edge Function module — NOT part of the Next.js build.

export type DigestAlert = {
  trigger_type: string;
  triggered_at: string;
  // deno-lint-ignore no-explicit-any
  details: any;
};

export type DigestStockGroup = {
  ticker: string;
  alerts: DigestAlert[];
};

const TRIGGER_LABELS: Record<string, string> = {
  stop_loss_breached: "STOP LOSS BREACHED",
  trim_target_reached: "TRIM TARGET",
  time_exit_due: "TIME EXIT DUE",
};

function triggerLabel(triggerType: string): string {
  return TRIGGER_LABELS[triggerType] ?? triggerType.toUpperCase();
}

/** One human-readable line summarizing an alert's `details` payload. */
function detailLine(alert: DigestAlert): string {
  const d = alert.details ?? {};
  switch (alert.trigger_type) {
    case "entry_zone_reached":
      return `price ${d.price} in [${d.entry_low}, ${d.entry_high}]`;
    case "stop_loss_breached":
      return `price ${d.price} <= stop ${d.stop_loss}`;
    case "trim_target_reached":
      return `price ${d.price} >= tier ${d.tier_price} (trim ${d.pct_of_position}%)`;
    case "earnings_approaching":
      return `earnings on ${d.earnings_date} (${d.days_out}d out)`;
    case "reassess_due":
      return `reassessment date ${d.reassess_date} has arrived`;
    default:
      try {
        return JSON.stringify(d);
      } catch {
        return "";
      }
  }
}

function escapeHtml(input: string): string {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function formatTime(iso: string): string {
  // HH:MM UTC — short, terminal-log-style timestamp.
  return `${iso.slice(11, 16)} UTC`;
}

/**
 * Groups flat `alert_log` rows (already joined with their stock's ticker)
 * by `stock_id`, ordered stock-by-stock in the order groups are given and
 * alert-by-alert in the order each group's `alerts` array is given
 * (`index.ts` is responsible for feeding rows in `triggered_at` order).
 */
export function groupAlertsByStock(
  rows: { stock_id: string; ticker: string; trigger_type: string; triggered_at: string; details: unknown }[],
): DigestStockGroup[] {
  const order: string[] = [];
  const byStockId = new Map<string, DigestStockGroup>();

  for (const row of rows) {
    let group = byStockId.get(row.stock_id);
    if (!group) {
      group = { ticker: row.ticker, alerts: [] };
      byStockId.set(row.stock_id, group);
      order.push(row.stock_id);
    }
    group.alerts.push({
      trigger_type: row.trigger_type,
      triggered_at: row.triggered_at,
      details: row.details,
    });
  }

  return order.map((id) => byStockId.get(id)!);
}

/**
 * Renders the digest as HTML: dark background, monospace-leaning
 * "terminal feed" tone, one block per stock with each trigger as a line —
 * per task-11-brief.md's explicit visual direction.
 */
export function renderDigestHtml(groups: DigestStockGroup[]): string {
  const dateLabel = new Date().toISOString().slice(0, 10);

  const blocks = groups
    .map((group) => {
      const lines = group.alerts
        .map((alert) => {
          return `      <div style="padding:2px 0;color:#c9d1d9;">` +
            `<span style="color:#3fb950;">[${formatTime(alert.triggered_at)}]</span> ` +
            `<span style="color:#f0883e;font-weight:600;">${escapeHtml(triggerLabel(alert.trigger_type))}</span> ` +
            `<span style="color:#8b949e;">${escapeHtml(detailLine(alert))}</span>` +
            `</div>`;
        })
        .join("\n");

      return (
        `  <div style="margin:0 0 20px 0;">\n` +
        `    <div style="color:#58a6ff;font-weight:700;font-size:14px;border-bottom:1px solid #30363d;padding-bottom:4px;margin-bottom:4px;">${escapeHtml(group.ticker)}</div>\n` +
        `${lines}\n` +
        `  </div>`
      );
    })
    .join("\n");

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Jarvis Daily Digest — ${dateLabel}</title>
  </head>
  <body style="margin:0;padding:24px;background:#0d1117;font-family:ui-monospace,SFMono-Regular,'SF Mono',Menlo,Consolas,monospace;">
    <div style="max-width:640px;margin:0 auto;">
      <div style="color:#e6edf3;font-size:16px;font-weight:700;margin-bottom:2px;">jarvis // daily digest</div>
      <div style="color:#8b949e;font-size:12px;margin-bottom:20px;">${dateLabel}</div>
${blocks}
      <div style="color:#484f58;font-size:11px;margin-top:24px;border-top:1px solid #21262d;padding-top:12px;">
        Generated by the poll-prices / daily-digest Supabase Edge Functions.
      </div>
    </div>
  </body>
</html>`;
}

/** Plain-text fallback rendering of the same content as `renderDigestHtml`. */
export function renderDigestText(groups: DigestStockGroup[]): string {
  const dateLabel = new Date().toISOString().slice(0, 10);
  const lines: string[] = [`jarvis // daily digest — ${dateLabel}`, ""];

  for (const group of groups) {
    lines.push(group.ticker);
    for (const alert of group.alerts) {
      lines.push(
        `  [${formatTime(alert.triggered_at)}] ${triggerLabel(alert.trigger_type)} ${detailLine(alert)}`,
      );
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}
